import type { Metadata } from "next";
import "./globals.css";
import SideBar from "../components/layout/side-bar";
import { Toaster } from "sonner";
import { PayrollProvider } from "../context/payroll-context";
import { ThemeProvider } from "next-themes";

export const metadata: Metadata = {
  title: "Cotopia Payroll",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-gray-200 dark:bg-gray-950 flex">
        <PayrollProvider>
          <ThemeProvider attribute="class">
            <Toaster position="bottom-right" />
            <SideBar />
            {children}
          </ThemeProvider>
        </PayrollProvider>
      </body>
    </html>
  );
}
