import type { Metadata } from "next";
import "./globals.css";
import SideBar from "../components/layout/side-bar";
import { Toaster } from "sonner";

export const metadata: Metadata = {
  title: "Cotopia Payroll",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-gray-200 flex gap-x-1">
        <Toaster position="bottom-right" />
        <SideBar />
        {children}
      </body>
    </html>
  );
}
