import type { Metadata } from "next";
import "./globals.css";
import SideBar from "../components/layout/side-bar";
import { Toaster } from "sonner";
import { PayrollProvider } from "../context/payroll-context";

export const metadata: Metadata = {
  title: "Cotopia Payroll",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <PayrollProvider>

        <body className="bg-gray-200 flex">
          <Toaster position="bottom-right" />
          <SideBar />
          {children}
        </body>

      </PayrollProvider>
    </html>
  );
}
